config/routes.rb
Progress360::Application.routes.draw do

  root :to => redirect('/dashboard')
  get '/dashboard' => 'dashboard#index', :as => :dashboard
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'components', to: 'components#index', as: 'components'

  resources :achievements, only: [:index, :new, :create, :destroy, :update]
  resources :trackers, only: [:show, :new, :create, :destroy] do
    resources :achievements, only: [:new, :create]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resource :learner, only: [:show, :edit, :update], as: :profile do
    resources :reports, except: [:destroy]
    resources :focus_positions, only: [:index]
    resources :focus_positions_updates, only: [:index]
  end

  get 'admin' => 'admin#show', :as => :admin
  namespace :admin do
    resources :learners, except: [:destroy]
    resources :trackers, only: [:index]
    resources :achievements, only: [:index]
  end

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
end

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>  
  <div id="errorExplanation">  
    <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>  
    <ul>  
    <% target.errors.full_messages.each do |msg| %>  
      <li><%= msg %></li>  
    <% end %>  
    </ul>  
  </div>  
<% end %>  

app/views/shared/_tracker_menu.html.erb
    <div class="btn-group tracker-dropdown">
      <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
        Choose a tracker <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li>
          <%= link_to "All", dashboard_path %>
        </li>
        <li class="divider"></li>
        <% current_user.trackers.all.each do |t| %>
          <% if t.trashed_at == nil %>
            <li>
              <%= link_to t.name, new_tracker_achievement_path(t) %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
    
    <%= link_to new_tracker_path, class: 'btn-action' do %>
      <span class="fui-plus-circle pull-right"></span>
    <% end %>