config/routes.rb
Progress360::Application.routes.draw do

  root :to => redirect('/dashboard')
  get '/dashboard' => 'dashboard#index', :as => :dashboard
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'components', to: 'components#index', as: 'components'

  resources :achievements, only: [:index, :new, :create, :destroy, :update]
  resources :trackers, only: [:show, :new, :create, :destroy] do
    resources :achievements, only: [:new, :create]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resource :learner, only: [:show, :edit, :update], as: :profile do
    resources :reports, except: [:destroy]
    resources :focus_positions, only: [:index]
    resources :focus_positions_updates, only: [:index]
  end

  get 'admin' => 'admin#show', :as => :admin
  namespace :admin do
    resources :learners, except: [:destroy]
    resources :trackers, only: [:index]
    resources :achievements, only: [:index]
  end

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
end

app/models/learner.rb
class Learner < ActiveRecord::Base
  has_secure_password
  validates :password, presence: true, :on => :create
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true

  has_many :achievements
  has_many :trackers
  has_many :focus_positions
  has_many :focus_positions_updates
  has_many :reports

  accepts_nested_attributes_for :focus_positions
  
  mount_uploader :avatar, AvatarUploader

  def self.anonymous
    find_by_email("anonymous@example.com") || create_anonymous!
  end

  def initialize_focus_positions!
    Focus.all.each do |focus|
      unless focus_positions.find_by_focus_id(focus.id)
        focus_positions.create!(focus: focus, position: FocusPosition::DEFAULT_POSITION)
      end
    end
  end
  
  private

  def self.create_anonymous!
    create!(name: "Anonymous",
            email: "anonymous@example.com",
            password: "Malice7Verse+whig",
            password_confirmation: "Malice7Verse+whig")
  end
end

app/controllers/admin/learners_controller.rb
class Admin::LearnersController < AdminController
  respond_to :html, :json

  def index
    @learners = Learner
      .joins("LEFT OUTER JOIN trackers AS active_trackers ON active_trackers.learner_id = learners.id 
        AND active_trackers.trashed_at IS NULL")
      .joins("LEFT OUTER JOIN trackers AS inactive_trackers ON inactive_trackers.learner_id = learners.id 
        AND inactive_trackers.trashed_at IS NOT NULL")
      .joins("LEFT OUTER JOIN achievements ON achievements.learner_id = learners.id")
      .joins("LEFT OUTER JOIN 
        ( SELECT a1.*
         FROM achievements AS a1
         LEFT JOIN achievements AS a2 ON a1.learner_id = a2.learner_id 
         AND a1.created_at < a2.created_at
         WHERE a2.learner_id IS NULL ) AS achievements_last ON achievements_last.learner_id = learners.id")
      .select("learners.*")
      .select("achievements_last.created_at AS achievement_date")
      .select("achievements_last.description AS achievement_description")
      .select("COUNT(DISTINCT active_trackers.id) AS active_count")
      .select("COUNT(DISTINCT inactive_trackers.id) AS inactive_count")
      .select("COUNT(DISTINCT achievements.id) AS achievements_count")
      .group('learners.id, achievements_last.created_at, achievements_last.description')

    respond_with @learners
  end

  def new
    @learner = Learner.new
  end

  def create
    @learner = Learner.new(learner_params)

    if @learner.save
      redirect_to admin_learners_path
    else
      render :new
    end
  end

  def edit
    @learner = Learner.find params[:id]
  end

  def update
    @learner = Learner.find params[:id]

    if @learner.update_attributes(learner_params)
      redirect_to admin_learners_path
    else
      render :edit
    end
  end

  private

  def learner_params
    params.require(:learner).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/learners_controller.rb
class LearnersController < InheritedResources::Base
  respond_to :html, :json
  actions :show, :edit, :update

  def update
    update! { profile_path }
  end

  private

  def update_resource(learner, attributes)
    super
    create_focus_positions_update_from_attributes(learner, attributes)
  end

  def create_focus_positions_update_from_attributes(learner, attributes)
    focus_positions_attributes = attributes.first["focus_positions_attributes"]
    if focus_positions_attributes
      FocusPositionsUpdate.create_for_learner_with_focus_positions_attributes!(learner, focus_positions_attributes)
    end
  end    
  
  def resource
    get_resource_ivar || set_resource_ivar(current_user)
  end

  def permitted_params
    params.permit(:learner =>
      ["name",
       "age",
       "class_year",
       "about_me",
       "about_me_as_a_learner",
       "hobbies_and_interests",
       "big_ambitions",
       "favourite_things",
       "best_thing_this_week",
       "avatar",
       focus_positions_attributes: [:id, :position]
      ]
    )
  end

  def begin_of_association_chain
    current_user
  end
end

app/views/learners/_short_profile.html.erb
<section class="profile full-height">
  <h1 class="visually-hidden">Profile</h1>

  <div class="avatar">
    <div class="avatar-cropper">
      <div class="avatar-constrainer">
        <% if user.avatar? %>
          <%= image_tag(user.avatar_url) %>
        <% else %>
          <%= image_tag "default_avatar.png", alt: "Avatar of %s" % user %>
        <% end %>
      </div>
    </div>
  </div>

  <dl>
    <dt class="visually-hidden">Name</dt>
    <dd class="heading fn"><%= user.name %></dd>
    <% if user.age.present? %>
      <dt>Age</dt>
      <dd><%= user.age %></dd>
    <% end %>
    <% if user.class_year.present? %>
      <dt>Class</dt>
      <dd><%= user.class_year %></dd>
    <% end %>

  </dl>
</section>

app/views/learners/edit.html.erb
<%= form_for resource, url: profile_path, builder: FormBuilder, html: { class: "l-profile" } do |f| %>
  <% content_for :sidebar do %>
    <%= render 'short_profile', user: current_user, f: f %>
  <% end %>

  <div class="full-profile">
    <h1 class="heading">Edit profile</h1>

    <label class="secondary-button image-upload-fake">
      Upload profile picture
      <%= f.file_field :avatar, class: "image-upload-real" %>
    </label>

    <%= f.label :name, class: 'field' do %>
      <% f.text_field :name %>
    <%- end -%>

    <%= f.label :age, class: 'field' do %>
      <% f.number_field :age, min: 0 %>
    <%- end -%>

    <%= f.label :class_year, "Class", class: 'field' do %>
      <% f.text_field :class_year %>
    <%- end -%>

    <%= f.label :about_me, class: 'field long-field' do %>
      <% f.text_area :about_me %>
    <%- end -%>

    <%= f.label :about_me_as_a_learner, class: 'field long-field' do %>
      <% f.text_area :about_me_as_a_learner %>
    <%- end -%>

    <%= f.label :hobbies_and_interests, 'My hobbies and interests', class: 'field long-field' do %>
      <% f.text_area :hobbies_and_interests %>
    <%- end -%>

    <%= f.label :big_ambitions, 'My big ambitions', class: 'field long-field' do %>
      <% f.text_area :big_ambitions %>
    <%- end -%>

    <%= f.label :favourite_things, '3 favourite things', class: 'field long-field' do %>
      <% f.text_area :favourite_things %>
    <%- end -%>

    <%= f.label :best_thing_this_week, class: 'field long-field' do %>
      <% f.text_area :best_thing_this_week %>
    <%- end -%>

    <%= f.submit "Save", class: "button" %>
    <%= link_to "Cancel", profile_path, class: "secondary-button" %>
  </div>
<% end %>

app/views/learners/show.html.erb
<%= content_for :sidebar do %>
  <%= render 'short_profile', user: current_user %>
<% end %>

<div class="full-profile">
  <section class="col-wrapper">
    <header>
      <h2 class="heading about-me">About me</h2>

      <%= link_to "Edit profile", edit_profile_path, class: "button edit" %>
      <%= link_to "Focus areas", profile_focus_positions_path, class: "button edit" %>
      <%= link_to "Go back", dashboard_path, class: "secondary-button" %>
    </header>
    
    <div class="col1">
      <p><%= current_user.about_me %></p>

      <% if current_user.about_me_as_a_learner.present? %>
        <section>
          <h2 class="sub-heading">About me as a learner</h2>
          <p><%= current_user.about_me_as_a_learner %></p>
        </section>
      <% end %>
      <% if current_user.hobbies_and_interests.present? %>
        <section>
          <h2 class="sub-heading">My hobbies and interests</h2>
          <p><%= current_user.hobbies_and_interests %></p>
        </section>
      <% end %>
      <% if current_user.big_ambitions.present? %>
        <section>
          <h2 class="sub-heading">My big ambitions</h2>
          <p><%= current_user.big_ambitions %></p>
        </section>
      <% end %>
      <% if current_user.favourite_things.present? %>
        <section>
          <h2 class="sub-heading">3 favourite things</h2>
          <p><%= current_user.favourite_things %></p>
        </section>
      <% end %>
      <% if current_user.best_thing_this_week.present? %>
        <section>
          <h2 class="sub-heading">Best thing this week</h2>
          <p><%= current_user.best_thing_this_week %></p>
        </section>
      <% end %>
    </div>

    <div class="col2">
      <%= form_for current_user, url: profile_path do |user_form| %>
        <%= user_form.fields_for :focus_positions do |positions_form| %>
          <%= render partial: 'focus_positions/form', locals: { focus_position: positions_form.object.decorate, form: positions_form } %>
        <% end %>
      <% end %>
    </div>

  </section>
</div>