config/routes.rb
Progress360::Application.routes.draw do

  root :to => redirect('/dashboard')
  get '/dashboard' => 'dashboard#index', :as => :dashboard
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'components', to: 'components#index', as: 'components'

  resources :achievements, only: [:index, :new, :create, :destroy, :update]
  resources :trackers, only: [:show, :new, :create, :destroy] do
    resources :achievements, only: [:new, :create]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resource :learner, only: [:show, :edit, :update], as: :profile do
    resources :reports, except: [:destroy]
    resources :focus_positions, only: [:index]
    resources :focus_positions_updates, only: [:index]
  end

  get 'admin' => 'admin#show', :as => :admin
  namespace :admin do
    resources :learners, except: [:destroy]
    resources :trackers, only: [:index]
    resources :achievements, only: [:index]
  end

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
end

app/views/navigation/_global_navigation.html.erb
<!-- views/navigation/_global_navigation.html.erb -->
<header>
  <nav>
    <ul id="nav">
      <% if current_user %>
        <li><%= link_to 'My Profile', profile_path, class: "my-profile" %></li>
        <li>
          <a id="nav-dashboard" href="/dashboard">
            My Activities and Achievements
          </a>
        </li>
        <li><%= link_to 'My Reports', profile_reports_path %></li>
        <li>
          <%= link_to logout_path, id: 'logout' do %>
            <%= image_tag 'logout-Icon.png', class: 'logout-icon' %>
            <span class='logout-link'>Logout</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>