config/routes.rb
Progress360::Application.routes.draw do

  root :to => redirect('/dashboard')
  get '/dashboard' => 'dashboard#index', :as => :dashboard
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'components', to: 'components#index', as: 'components'

  resources :achievements, only: [:index, :new, :create, :destroy, :update]
  resources :trackers, only: [:show, :new, :create, :destroy] do
    resources :achievements, only: [:new, :create]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resource :learner, only: [:show, :edit, :update], as: :profile do
    resources :reports, except: [:destroy]
    resources :focus_positions, only: [:index]
    resources :focus_positions_updates, only: [:index]
  end

  get 'admin' => 'admin#show', :as => :admin
  namespace :admin do
    resources :learners, except: [:destroy]
    resources :trackers, only: [:index]
    resources :achievements, only: [:index]
  end

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :learner

  default_scope { order(created_at: :desc) }
end

app/controllers/reports_controller.rb
class ReportsController < InheritedResources::Base
  respond_to :html, :json
  belongs_to :learner, instance_name: 'current_user'
  
  before_filter :set_trackers

  def create
    create! { profile_reports_url }
  end

  def update
    update! { profile_reports_url }
  end

  def new
    @foci = Focus.all
    @current_trackers = begin_of_association_chain.trackers
    @achievements = begin_of_association_chain.achievements.decorate
    new!
  end

  def edit
    @foci = Focus.all
    @current_trackers = begin_of_association_chain.trackers.where("created_at <= ?", resource.created_at)
    @achievements = begin_of_association_chain.achievements.where("created_at <= ?", resource.created_at).decorate 
    edit!
  end

  private

  def begin_of_association_chain
    current_user
  end

  def permitted_params
    params.permit(:report => [:about_me, :where_i_started, :where_i_am_now, :where_i_want_to_be, :teacher_comment])
  end

  def collection
    @reports ||= super.decorate
  end

  def resource
    @report ||= super.decorate
  end

  def build_resource
    @report ||= super.decorate
    @report.about_me ||= current_user.about_me
    
    return @report
  end

end

app/views/reports/_form.html.erb
<div class="new-report">
  <header class="report-header">
    <h1><%= current_user.name %></h1>
    <h2><%= resource.name %></h2>
  </header>

  <%= form_for [:profile, resource] do |f| %>

    <h2 class="heading overview">Overview</h2>

    <div>
      <%= f.label :about_me %>
      <%= f.text_area :about_me%>
    </div>

    <h2 class="heading border-top">Activity Summary</h2>
    <table class="table">
      <thead>
        <th>Focus Area</th>
        <th>Easy Trackers</th>
        <th>Medium Trackers</th>
        <th>Hard Trackers</th>
        <th>Logged Activity</th>
      </thead>
      <tbody>
        <% @foci.each do |focus| %>
          <tr class="<%= cycle("odd", "even") %>">
            <td><%= focus.name %></td>
            <td><%= @current_trackers.select { |c| c.focus == focus && c.easy? }.count %></td>
            <td><%= @current_trackers.select { |c| c.focus == focus && c.medium? }.count %></td>
            <td><%= @current_trackers.select { |c| c.focus == focus && c.hard? }.count %></td>
            <td><%= @achievements.select { |a| a.focus == focus }.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div>
      <%= f.label :where_i_started, 'Where I started' %>
      <%= f.text_area :where_i_started %>
    </div>

    <div>
      <%= f.label :where_i_am_now, 'Where I am now' %>
      <%= f.text_area :where_i_am_now %>
    </div>

    <div>
      <%= f.label :where_i_want_to_be, 'Where I want to be' %>
      <%= f.text_area :where_i_want_to_be %>
    </div>

    <div>
      <%= f.label :teacher_comment %>
      <%= f.text_area :teacher_comment %>
    </div>

    <%= f.submit 'Save', class: 'button save' %>
    <%= link_to "Cancel", profile_reports_path, class: 'button secondary-button cancel' %>

  <% end %>

  <h2 class="heading border-top">Appendix</h2>
  <ul>
    <%= render @achievements %>  
  </ul>
</div>

app/views/reports/edit.html.erb
<%= render 'form' %>

app/views/reports/index.html.erb
<div class="build-report">
  <%= link_to 'Build Report', new_profile_report_path, class: "button" %>

  <h2>View Previous Reports</h2>
  <ul>
    <% collection.each do |i| %>
      <li><%= link_to i.name, edit_profile_report_path(i) %></li>
    <% end %>  
  </ul>
</div>

app/views/reports/new.html.erb
<%= render 'form' %>